Fix Win64 build
  C:/lo/core2/xmloff/qa/unit/draw.cxx(856): error C2672: 'CppUnit::assertEquals': no matching overloaded function found
  C:/lo/core2/xmloff/qa/unit/draw.cxx(856): error C2782: 'void CppUnit::assertEquals(const T &,const T &,CppUnit::SourceLine,const std::string &)': template parameter 'T' is ambiguous
  C:\lo\build2\workdir\UnpackedTarball\cppunit\include\cppunit/TestAssert.h(161): note: see declaration of 'CppUnit::assertEquals'
  C:/lo/core2/xmloff/qa/unit/draw.cxx(856): note: could be 'sal_Int32'
  C:/lo/core2/xmloff/qa/unit/draw.cxx(856): note: or       'int'
  C:/lo/core2/xmloff/qa/unit/draw.cxx(856): error C2784: 'void CppUnit::assertEquals(const T &,const T &,CppUnit::SourceLine,const std::string &)': could not deduce template argument for 'const T &' from 'sal_Int32'
  C:\lo\build2\workdir\UnpackedTarball\cppunit\include\cppunit/TestAssert.h(161): note: see declaration of 'CppUnit::assertEquals'

after commit d197333db0fbf6647dce19e20bee265885224a74 "[API CHANGE]
sd pdfium: add page number when saving/loading pdf pages as images",
2025-01-29.

This is not needed in master, where the posted original change was
fixed after a failure in CI.

Change-Id: Icaeeaf2f91b3e400f19499e7cd65667a16420266
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/182269
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>