Silence strange -Wclobbered with recent GCC 14
...seen at least with some (--enable-dbgutil --enable-otpimized etc.)
configuration and a recent GCC 14 trunk,

> vcl/source/filter/png/PngImageReader.cxx: In function ‘bool {anonymous}::reader(SvStream&, Graphic&, GraphicFilterImportFlags, BitmapScopedWriteAccess*, BitmapScopedWriteAccess*)’:
> vcl/source/filter/png/PngImageReader.cxx:361:16: error: variable ‘bSupportsBitmap32’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
>   361 |     const bool bSupportsBitmap32 = bFuzzing || ImplGetSVData()->mpDefInst->supportsBitmap32();
>       |                ^~~~~~~~~~~~~~~~~

Reviewed-on: https://gerrit.libreoffice.org/c/core/+/165823
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
(cherry picked from commit 2bcd9fe0fa10339294e6ab820498fa18334e02f3)
(cherry picked from commit 344adf0e44ea876e5e3222a05f57898cc0682eac)

Extend silence strange -Wclobbered with GCC <= 14

See 2bcd9fe0fa10339294e6ab820498fa18334e02f3
Silence strange -Wclobbered with recent GCC 14

Reviewed-on: https://gerrit.libreoffice.org/c/core/+/166994
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
Tested-by: Julien Nabet <serval2412@yahoo.fr>
(cherry picked from commit e783a1c09093f3dbaf778661b77a2d5872a2029d)
(cherry picked from commit 8f6c1722284b38483cca3bbdeabc5e35edfc1c5e)

The -Wclobbered still hits with GCC 15

...(same as documented at 2bcd9fe0fa10339294e6ab820498fa18334e02f3 "Silence
strange -Wclobbered with recent GCC 14"), at least with
gcc-c++-15.2.1-1.fc43.2.x86_64 (but is no longer relevant on master after
6f92f2cb118cc97e57c57e02bef491ecf39b1f4a "ofz#435489660 Direct-leak from
vcl::PngImageReader::read")

Change-Id: I2dcc7a51042e7966e5fc7f4b02e49a7fee27fc92
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/191688
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
(cherry picked from commit 35fb38a7dc4762c3e238c74b3c91bdf3efa5a4bb)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/191782
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>