rhbz#2354168 configure: workaround bogus "dbus-1" libs
DBUS_LIBS contains -L/usr/lib64/pkgconfig/../../lib64 which eventually
causes link failure:
  desktop/source/lib/init.cxx:6451: error: undefined reference to 'ublock_getCode_77'

Reportedly realpath(1) is available even on macOS now so use it to
resolve these paths.

Change-Id: I754447ad23982918d6f8e80f839112db22b75205
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/189864
Tested-by: Jenkins
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
(cherry picked from commit 457872f8cac849b319ad4f88a94c8390aa9e3df7)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/189879
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>
(cherry picked from commit db867ee5d6b6a239a7d822233ad022d18962ccd4)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/191788