MSVC 2022 Preview: One HAVE_CPP_CONSTEVAL blocker down, one up
While the previously known issue appears to be fixed in VS 2022 Preview 17.9.0
Preview 5.0, a new one showed up that now caused

> sal/qa/rtl/oustringbuffer/test_oustringbuffer_assign.cxx(63): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'rtl::OUStringLiteral<2>'
> sal/qa/rtl/oustringbuffer/test_oustringbuffer_assign.cxx(63): note: Invalid aggregate initialization
> sal/qa/rtl/oustringbuffer/test_oustringbuffer_assign.cxx(63): note: too many initializers

etc.

Change-Id: Ia74a8d6454bb5f15c0af4d3cf29989342f2eef7a
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/163072
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/170423
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>