Fix build [-Werror=unused-parameter]
desktop/source/lib/init.cxx:5430:51: error: unused parameter ‘pThis’ [-Werror=unused-parameter]
 5430 | static char* getLanguages(LibreOfficeKitDocument* pThis, const char* pCommand)
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~

After 7fb089be113f3f95d9a13e3aafafc64107301d1d.

Change-Id: If4d9a751e4d32df4d8b854e197da5e8eb7e96d9e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/146906
Reviewed-by: Andras Timar <andras.timar@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>