WaE: WhitespaceToSpace() spurious -Werror=maybe-uninitialized
vcl/source/helper/strhelper.cxx:366:9: error: ‘pBuffer[-1]’ may be used uninitialized [-Werror=maybe-uninitialized]

I see this with gcc 13 too

Change-Id: I3ddc5fadb9177827e6cd49f5b6366a79204e95c4
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/152469
Tested-by: Jenkins
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>
(cherry picked from commit 36ec021c6eafe80caefbedbbe674bd1ee0a9429a)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/152445
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>